#!/bin/sh
BRANCH=${PLUGIN_COMMIT_BRANCH:-$DRONE_COMMIT_BRANCH}
REMOTE_URL=${PLUGIN_REMOTE_URL:-$DRONE_REMOTE_URL}
SHA=${PLUGIN_COMMIT_SHA:-$DRONE_COMMIT_SHA}
FLAGS=""

if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${REMOTE_URL}
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${BRANCH}:
git checkout ${SHA} -b ${BRANCH}